#!/bin/bash


# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         000000
berryc unfocus_color       000000
berryc inner_focus_color   000000
berryc inner_unfocus_color 000000
berryc text_focus_color    FFFFFF
berryc text_unfocus_color  FFFFFF

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Sans Regular-9"
berryc edge_gap 80 30 30 30

#Auto start
polybar main &
hsetroot -cover $HOME/.config/berry/987090.jpg
#mio-purer-than-your-waifu.png
sxhkd -c ~/.config/berry/sxhkdrc &
